#!/usr/bin/env python
"""Regenerate the GGML regression-test fixtures.

Two artefacts:

  fixtures/regression_input.f32
      32000 raw little-endian float32: 16000 mic samples then 16000 ref
      samples. Matches the seed used by pytorch/tests/test_checkpoints.py
      so the same input flows through both regression suites.

  fixtures/<gguf_basename>.out.f32
      16000 raw little-endian float32: the model's output on the input
      above. Generated by running the test_regression binary in --save
      mode.

Usage:
    python tests/regenerate_fixtures.py --gguf <path-to-gguf> \\
        [--test-bin <path-to-built-test_regression>]

If --test-bin is omitted, we look in build/bin/test_regression and
build-cpu/bin/test_regression. Build it first with cmake.

Native-engine fixtures (localvqe-v1.4-aec-200K-native-{f32,bf16}.out.f32)
are produced by the native_test harness instead (kernel-path specific,
znver4-only, only built with -DLOCALVQE_NATIVE_ENGINE=ON — they guard
the development CPU, not portable builds):

    native_test[_f32] <gguf> --reg-input fixtures/regression_input.f32 \\
        --save fixtures/localvqe-v1.4-aec-200K-native-<kind>.out.f32

PROVENANCE 2026-06-12: the v1 .. v1.3 fixtures were regenerated after
fixing a frame-state copy-ordering bug in process_frame_graph
(overlapping gallocr regions could clobber the history copy-back).
The pre-fix fixtures embedded the bug's output; against the PyTorch
reference (same seeded input, scale-corrected for the documented v2+
OLA convention factor of exactly 2.0) the corrected code matches
PyTorch to ~3.5e-5 relative where the old fixtures deviated by 1.5e-2
(v1.2) and 1.5e-1 (v1.1) — and far worse on real audio. v1 and v1.3
regenerated byte-identical (unaffected).
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures"

# Mirrors pytorch/tests/test_checkpoints.py — keep in lockstep.
_INPUT_SEED = 20260510
_INPUT_LEN = 16000

# Prime-coverage fixture (standalone delay priming). The standard fixture is
# independent random noise, which has no echo structure — so the GCC finds no
# delay and daf_prime_delay is a no-op. This one is a far-end ref with a
# delayed, attenuated echo in the mic, longer than the 1.024 s GCC window, so
# prime locks a known bulk delay and aligns the filter from frame 0. Pure numpy
# + fixed seed → reproducible, no licensed audio committed.
_PRIME_SEED = 20260614
_PRIME_LEN = 48000     # 3 s @ 16 kHz (> the 1.024 s GCC window)
_PRIME_DELAY = 3000    # ~187 ms bulk delay (>> the 128-sample block)


def _generate_prime_input(out_path: Path):
    import numpy as np
    rng = np.random.default_rng(_PRIME_SEED)
    ref = (rng.standard_normal(_PRIME_LEN) * 0.3).astype(np.float32)
    mic = np.zeros(_PRIME_LEN, dtype=np.float32)
    # 3-tap echo path at the bulk delay (direct + two reflections)
    for d, g in ((_PRIME_DELAY, 0.6), (_PRIME_DELAY + 53, 0.25),
                 (_PRIME_DELAY + 211, 0.12)):
        mic[d:] += ref[:_PRIME_LEN - d] * g
    mic += (rng.standard_normal(_PRIME_LEN) * 0.02).astype(np.float32)  # near-end
    buf = np.concatenate([mic, ref]).astype(np.float32)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    buf.tofile(out_path)
    print(f"[ok] wrote {out_path} ({buf.size} float32, "
          f"{out_path.stat().st_size} bytes)")


def _generate_input(out_path: Path):
    try:
        import torch
    except ImportError:
        sys.exit(
            "PyTorch is required to regenerate the input fixture. "
            "Install with: pip install torch"
        )
    g = torch.Generator().manual_seed(_INPUT_SEED)
    mic = torch.randn(1, _INPUT_LEN, generator=g).contiguous().view(-1)
    ref = torch.randn(1, _INPUT_LEN, generator=g).contiguous().view(-1)
    buf = torch.cat([mic, ref]).to(torch.float32).cpu().numpy()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    buf.tofile(out_path)
    print(f"[ok] wrote {out_path} ({buf.size} float32, {out_path.stat().st_size} bytes)")


def _find_test_binary(repo_root: Path) -> Path | None:
    for rel in ("build/bin/test_regression", "build-cpu/bin/test_regression"):
        p = repo_root / rel
        if p.exists():
            return p
    return None


def _generate_output(test_bin: Path, gguf_path: Path, input_path: Path, out_path: Path):
    cmd = [
        str(test_bin),
        "--gguf", str(gguf_path),
        "--gguf-name", gguf_path.name,
        "--input", str(input_path),
        "--save", str(out_path),
    ]
    print("$", " ".join(cmd))
    env = os.environ.copy()
    # Ensure libggml-cpu-*.so next to the binary is found.
    env["LD_LIBRARY_PATH"] = str(test_bin.parent) + ":" + env.get("LD_LIBRARY_PATH", "")
    subprocess.run(cmd, check=True, env=env)
    print(f"[ok] wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--gguf", type=Path, default=None, help="Path to the .gguf file")
    parser.add_argument("--test-bin", type=Path, default=None,
                        help="Path to the built test_regression binary")
    parser.add_argument("--prime-input", action="store_true",
                        help="Only (re)generate fixtures/regression_input_prime.f32 "
                             "(numpy; the prime expected output is produced "
                             "separately by running the test_regression binary "
                             "with --input regression_input_prime.f32 --save "
                             "<stem>.prime.out.f32).")
    args = parser.parse_args()

    if args.prime_input:
        _generate_prime_input(FIXTURES / "regression_input_prime.f32")
        return

    if args.gguf is None:
        sys.exit("--gguf is required (or pass --prime-input)")
    if not args.gguf.exists():
        sys.exit(f"GGUF not found: {args.gguf}")

    repo_root = HERE.parent.parent  # tests/ → ggml/ → repo
    test_bin = args.test_bin or _find_test_binary(repo_root / "ggml")
    if not test_bin or not test_bin.exists():
        sys.exit(
            "test_regression binary not found. Build it first:\n"
            "  cmake -B ggml/build -S ggml && cmake --build ggml/build -j --target test_regression\n"
            "or pass --test-bin <path>."
        )

    input_path = FIXTURES / "regression_input.f32"
    output_path = FIXTURES / f"{args.gguf.stem}.out.f32"

    _generate_input(input_path)
    _generate_output(test_bin, args.gguf, input_path, output_path)


if __name__ == "__main__":
    main()
