# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Checkout obs
      uses: actions/checkout@v7
      with:
        submodules: recursive
        repository: obsproject/obs-plugintemplate
        path: obs-plugintemplate
    - name: Install pkgconfig
      run: choco install pkgconfiglite
    # - name: Build assets
    #   run: |
    #     rm ggml/tests/*.cpp
    #     cmake -S ggml -B ggml/build -DCMAKE_BUILD_TYPE=Release -DLOCALVQE_BUILD_SHARED=ON -DLOCALVQE_BUILD=ON
    #     (Get-Content ggml/CMakeLists.txt).Replace(' SHARED ', ' STATIC ') | Set-Content ggml/CMakeLists.txt
    #     (Get-Content ggml/CMakeLists.txt).Replace('x86_64|AMD64|amd64', 'XXXXXXXXXXXXX') | Set-Content ggml/CMakeLists.txt
    #     cmake --build ggml/build
    - name: Copy plugin assets
      run: |
        cp obs-plugin/src obs-plugintemplate -Recurse -Force
        cp obs-plugin/data obs-plugintemplate -Recurse -Force
        cp ../ggml/vendor obs-plugintemplate -Recurse -Force
        (Get-Content obs-plugintemplate/CMakeLists.txt).Replace('src/plugin-main.c', 'src/plugin-main.c src/localvqe-filter.c ../ggml/localvqe_api.cpp') | Set-Content obs-plugintemplate/CMakeLists.txt
        (Get-Content obs-plugintemplate/CMakePresets.json).Replace('"CMAKE_COMPILE_WARNING_AS_ERROR": true', '"CMAKE_COMPILE_WARNING_AS_ERROR": false') | Set-Content obs-plugintemplate/CMakePresets.json
        (Get-Content obs-plugintemplate/buildspec.json).Replace('plugintemplate-for-obs', 'obs-localvqe') | Set-Content obs-plugintemplate/buildspec.json
        (Get-Content obs-plugintemplate/buildspec.json).Replace('Plugin Template for OBS', 'Local Voice Quality Enhancement') | Set-Content obs-plugintemplate/buildspec.json
        (Get-Content ggml/CMakeLists.txt).Replace('${CMAKE_CURRENT_SOURCE_DIR}', '${CMAKE_CURRENT_SOURCE_DIR}/../ggml') | Set-Content ggml/CMakeLists.txt
        echo 'find_path(LOCALVQE_INCLUDE_DIR NAMES localvqe_api.h HINTS ${CMAKE_SOURCE_DIR}/../ggml)' >> obs-plugintemplate/CMakeLists.txt
        echo 'target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${LOCALVQE_INCLUDE_DIR})' >> obs-plugintemplate/CMakeLists.txt
        echo 'include(../ggml/CMakeLists.txt)' >> obs-plugintemplate/CMakeLists.txt
        
      # echo 'add_subdirectory(../ggml/vendor/ggml ggml_build)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'add_library(dvqe_common STATIC ../ggml/common.cpp)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'target_include_directories(dvqe_common PUBLIC ../ggml)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'target_link_libraries(dvqe_common PUBLIC ggml)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'add_library(dvqe_graph STATIC ../ggml/localvqe_graph.cpp ../ggml/model_hash.cpp)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'target_link_libraries(dvqe_graph PUBLIC dvqe_common)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'add_library(localvqe_shared STATIC ../ggml/localvqe_api.cpp)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'target_link_libraries(localvqe_shared PRIVATE dvqe_graph)' >> obs-plugintemplate/CMakeLists.txt
      # echo 'target_compile_definitions(localvqe_shared PRIVATE LOCALVQE_BUILD)' >> obs-plugintemplate/CMakeLists.txt

    - name: Build plugin
      run: pwsh -File obs-plugintemplate/.github/scripts/Build-Windows.ps1
    - name: Upload plugin
      uses: actions/upload-artifact@v7
      with:
        name: obs-plugin
        path: obs-plugintemplate
    - name: Upload assets
      uses: actions/upload-artifact@v7
      with:
        name: assets
        path: ggml/build

    
    
